apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  restartPolicy: Never
  containers:
    - name: debug
      image: "stvasyl/debug-container:latest"
      imagePullPolicy: Always
      command:
        - /bin/sleep
        - "14d"
      env:
      - name: DOCKER_HOST
        value: unix:///var/run/docker.sock
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      volumeMounts:
      - name: dind-sock
        mountPath: /var/run
    - name: dind
      image: docker:dind
      imagePullPolicy: Always
      args:
      - dockerd
      - --host=unix:///var/run/docker.sock
      - --group=$(DOCKER_GROUP_GID)
      securityContext:
        privileged: true
      env:
      - name: DOCKER_HOST
        value: unix:///var/run/docker.sock
      - name: DOCKER_GROUP_GID
        value: "1001"
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 1
          memory: 1Gi
      volumeMounts:
      - name: dind-sock
        mountPath: /var/run
  volumes:
  - name: dind-sock
    emptyDir: {}
